export const FEATURE_FLAGS = {
  // When true, new stores will be assigned an autogenerated storeCode
  // Generation spec: increment Firestore counter, base36 encode, prefix 'TOV', pad to 8, ensure uniqueness
  AUTO_STORE_CODE: true
};
